name: flutterquiz
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.11+12

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  apple_sign_in_safety: ^0.0.6
  assets_audio_player: ^3.0.4+1
  cached_network_image: ^3.0.0
  cloud_firestore: ^4.0.3
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.3
  facebook_audience_network: ^1.0.0-nullsafety.0
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_exif_rotation: ^0.5.1
  flutter_html: ^3.0.0-alpha.1
  flutter_local_notifications: ^16.2.0
  flutter_localizations:
    sdk: flutter
  flutter_login_facebook: ^1.2.0
  flutter_svg: ^2.0.9
  google_fonts: ^4.0.4
  google_mobile_ads: ^4.0.0
  google_sign_in: ^6.2.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  http: ^0.13.3
  unity_ads_plugin: ^0.3.4
  image_picker: ^1.0.5
  in_app_purchase: ^3.0.4
  internet_connection_checker: ^1.0.0+1
  ios_insecure_screen_detector: ^0.0.2

  intl_phone_field: ^3.1.0
  just_audio: ^0.9.12
  launch_review: ^3.0.1
  lottie: ^2.1.0
  octo_image: ^2.0.0
  #otp_autofill: ^1.1.0
  package_info_plus: ^3.0.1
  path_provider: ^2.0.2
  pin_code_fields: ^8.0.1
  scratcher: ^2.1.0
  screenshot: ^2.1.0
  share_plus: ^6.2.0
  shared_preferences: ^2.0.6
  sms_autofill: ^2.2.0
  url_launcher: ^6.0.12
  wakelock: ^0.6.1+2
  webview_flutter: ^4.4.2
  country_code_picker: ^3.0.0
  flutter_windowmanager: ^0.2.0
  encrypt:
  flutter_tex: ^4.0.3+4
  modal_bottom_sheet: ^2.1.2
  connectivity_plus_web: ^1.2.5
  package_info_plus_web: ^2.0.0
  share_plus_web: ^3.1.0


dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_localizations:
  sdk: flutter
  intl: any
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/images/profile/

    - assets/images/emojis/
    - assets/images/coins/

    - assets/languages/
    - assets/animations/

    - assets/sounds/
    - assets/files/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
